#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL81Dialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#server:
#  port: 9091
#
